config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users, except: [:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :words, only: [:index]
  resources :categories, only: [:index]

  scope '/lessons' do
    get ':id' => 'lessons#show', as: :lesson
    post ':category_id' => 'lessons#create'
  end

  namespace :admin do
    root 'static_pages#index'
    resources :users,        only:   [:index, :destroy]
    resources :categories,   except: [:show]
    resources :words,        except: [:show]
  end
  
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is the E-Learning application internship project
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Email: 
  <a href="mailto:hua.viet.ngoc@framgia.com">hua.viet.ngoc@framgia.com</a>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-md-3">
      <%= show_image(current_user.admin? ? :admin : :user, current_user.avatar.url,
          alt: current_user.fullname, class: "user-avatar-home") %>
      <h4 class="username"><%= current_user.fullname %></h4>
      <p style="text-align:center">
        Learned: <%= current_user.learned_words.count %> words
      </p>
    </div>
    <div class="seperator-side col-md-9">
      <div class="row col-md-offset-1">
        <%= link_to "Words", words_path, class: "col-md-5 btn btn-lg btn-default" %>
        <%= link_to "Lessons", categories_path, 
                  class: "col-md-offset-1 col-md-5 btn btn-lg btn-default" %>
      </div>
      <div class="row col-md-offset-1">
        <h3>Activities</h3>
        <% current_user.following_activities.each do |activity| %>
          <%= render 'shared/activity', activity: activity %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the E-Learning App</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>