config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users, except: [:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :words, only: [:index]
  resources :categories, only: [:index]

  scope '/lessons' do
    get ':id' => 'lessons#show', as: :lesson
    post ':category_id' => 'lessons#create'
  end

  namespace :admin do
    root 'static_pages#index'
    resources :users,        only:   [:index, :destroy]
    resources :categories,   except: [:show]
    resources :words,        except: [:show]
  end
  
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc {|attributes| attributes[:content].blank?}

  validates :name,  presence: true, uniqueness: true
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
    @words = Word.page params[:page]
  end

  def new
    @word = Word.new
    4.times {@word.answers.build}
  end  

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = "A new word is created successfully"
      redirect_to edit_admin_word_path(@word)
    else
      render 'new'
    end
  end

  def edit
    @word = Word.find_by_id params[:id]
  end

  def update
    @word = Word.find_by_id params[:id]
    if @word.update_attributes word_params
      flash[:success] = "Word updated"
      redirect_to edit_admin_word_path(@word)
    else
      render 'edit'
    end
  end

  def destroy
    Word.find_by_id(params[:id]).destroy
    flash[:success] = "Word deleted"
    redirect_to admin_words_path
  end

  private

  def word_params
    params.require(:word).permit(:name, :category_id,
      answers_attributes: [:id, :content, :correct, :_destroy])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    category = Category.find_by_id(params[:category_id])
    if params[:word_type] == "learned"
      @words = current_user.learned_words category
    elsif params[:word_type] == "not learned"
      @words = current_user.not_learned_words category
    else
      @words = category.nil? ? Word.all : category.words
    end

    @words = @words.order(name: params[:sort]) unless params[:sort].blank?
    @words = @words.page params[:page]
  end
end

app/views/admin/words/_answer.html.erb
<div class="row">
  <div class="col-sm-6"><%= f.text_field :content, class: "form-control" %></div>
  <div class="col-sm-3"><%= f.check_box :correct %></div>
  <div class="col-sm-3">
    <%= f.check_box :_destroy %>
    <%= link_to "delete", "javascript:void(0);", class: "remove-answer" %>
  </div>
</div>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.id %></td>
  <td><%= word.name %></td>
  <td><%= "Meaning Here" %></td>
  <td><%= word.category.name %></td>
  <td><%= link_to "edit", edit_admin_word_path(word) %>
      <%= link_to "delete", admin_word_path(word), method: :delete,
                                  data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/admin/words/edit.html.erb
<% provide(:title, 'Edit word') %>
<h1>Edit word</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:admin, @word]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :category %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, 
            {selected: @word.category.id}, {class: 'form-control'}) %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <hr />
      <h4>Answers:</h4>
      <div id="edit_answers">
        <div class="row" style="margin-bottom:10px">
          <div class="col-sm-6">Content</div>
          <div class="col-sm-3">Right answer?</div>
          <div class="col-sm-3">Action</div>
        </div>
        <%= f.fields_for :answers do |builder| %>
          <%= render "answer", f: builder %>
        <% end %>
        <div class="row" style="margin-bottom:10px">
          <div class="col-sm-offset-9 col-sm-3">
          <%= link_to "new", "javascript:void(0);", id: "add_answer" %>
          </div>
        </div>
      </div>

      <% f.fields_for :answers, Answer.new, child_index: "new_answer" do |builder| %>
        <% @template = render "answer", f: builder %>
      <% end %>

      <%= f.submit "Update word", class: "btn btn-primary" %>
    <% end %>

    <div id="answer_template"><%= @template %></div>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide(:title, 'All words') %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Word</th>
      <th>Meaning</th>
      <th>Category</th>
      <th>Action <%= link_to "new", new_admin_word_path %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @words %>
  </tbody>
</table>
<%= paginate @words %>

app/views/admin/words/new.html.erb
<% provide(:title, 'Create new word') %>
<h1>Create new word</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:admin, @word]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :category %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, 
            {}, {class: 'form-control'}) %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <hr />
      <h4>Answers:</h4>
      <div id="edit_answers">
        <div class="row" style="margin-bottom:10px">
          <div class="col-sm-6">Content</div>
          <div class="col-sm-3">Right answer?</div>
          <div class="col-sm-3">Action</div>
        </div>
        <%= f.fields_for :answers do |builder| %>
          <%= render "answer", f: builder %>
        <% end %>
        <div class="row" style="margin-bottom:10px">
          <div class="col-sm-offset-9 col-sm-3">
          <%= link_to "new", "javascript:void(0);", id: "add_answer" %>
          </div>
        </div>
      </div>

      <% f.fields_for :answers, Answer.new, child_index: "new_answer" do |builder| %>
        <% @template = render "answer", f: builder %>
      <% end %>

      <%= f.submit "Create new word", class: "btn btn-primary" %>
    <% end %>

    <div id="answer_template"><%= @template %></div>
  </div>
</div>